#pragma once
#include <windows.h>
#include <string.h>
#include <string>
#include <iostream>
#include <stdio.h> 
#include <tchar.h> 
#include <stdio.h>
//#include <strsafe.h>
#include <vector>
#include <sstream>
#include <fstream>